version: '3.8'

services:
  uber-cheats:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=https://ubercheats.freas.me
    container_name: uber-cheats
    ports:
      - "3001:3000"
      - "8001:8000"
    volumes:
      - ./uber_deals.db:/app/uber_deals.db
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  uber-cheats-data:
    external: true
  uber-cheats-env:
    external: true 
