version: '3.8'

services:
  uber-cheats:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Frontend
      - "8000:8000"  # Backend
    volumes:
      - ./uber_deals.db:/app/uber_deals.db
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/deals"]
      interval: 30s
      timeout: 10s
      retries: 3 