version: '3.8'

services:
  uber-cheats:
    image: akfreas/uber-cheats:latest
    restart: unless-stopped
    ports:
      - "80:3000"  # Map container port 3000 to host port 80 (for frontend)
      - "8000:8000"  # Backend API
    volumes:
      - ./uber_deals.db:/app/uber_deals.db
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/deals"]
      interval: 30s
      timeout: 10s
      retries: 3