version: '3.8'

services:
  uber-cheats:
    image: akfreas/uber-cheats:latest
    restart: unless-stopped
    ports:
      - "3001:3000"
      - "8001:8000"
    volumes:
      - ./uber_deals.db:/app/uber_deals.db
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/deals"]
      interval: 30s
      timeout: 10s
      retries: 3